name: Deploy Static HTML to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

env:
  APP_LOCATION: "/"  # Ruta raíz donde está tu index.html
  API_LOCATION: ""   # Vacío porque no tienes API
  APP_ARTIFACT_LOCATION: ""  # Vacío porque no necesitas build

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Deploy Static HTML
    steps:
      - uses: actions/checkout@v4
        
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          skip_app_build: true  # Crucial para contenido estático

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
