name: Deploy Static HTML to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

env:
  APP_LOCATION: "/"                 # Directorio raíz
  HTML_FILE: "webcloud.html"        # Nombre de tu archivo HTML
  APP_ARTIFACT_LOCATION: "public"   # Carpeta de salida

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          # Crea package.json con el nombre correcto del archivo HTML
          echo '{
            "name": "static-html-app",
            "version": "1.0.0",
            "scripts": {
              "build": "mkdir -p public && cp webcloud.html public/index.html && echo \"HTML deployed successfully\""
            }
          }' > package.json
          
          # Verifica que el archivo HTML existe
          if [ ! -f "$HTML_FILE" ]; then
            echo "Error: $HTML_FILE not found!"
            exit 1
          fi

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          app_build_command: "npm run build"
          output_location: "index.html"
          skip_app_build: false

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed"
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
