name: Deploy Static HTML to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

env:
  APP_LOCATION: "/"                 # Directorio raíz
  HTML_FILE: "webcloud.html"        # Nombre de tu archivo HTML
  APP_ARTIFACT_LOCATION: "public"   # Carpeta de salida (creada automáticamente)

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dummy package.json
        run: |
          echo '{
            "name": "static-html-app",
            "version": "1.0.0",
            "scripts": {
              "build": "mkdir -p public && cp $HTML_FILE public/index.html && echo \"HTML copied successfully\""
            }
          }' > package.json
          cat package.json  # Opcional: verifica el contenido

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          app_build_command: "npm run build"
          output_location: "index.html"  # Azure buscará este archivo en la carpeta public

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
